include: package:flutter_lints/flutter.yaml

linter:
  rules:
     avoid_print: false
     prefer_single_quotes: true
     avoid_renaming_method_parameters: true
     avoid_bool_literals_in_conditional_expressions: true
     prefer_if_null_operators: true
     prefer_is_not_empty: true
     prefer_is_empty: true
